wamv_camera:
    - name: middle_camera
      x: 0.75
      P: ${radians(15)}
    - name: left_camera
      x: 0.75
      y: -0.3
      P: ${radians(15)}
      Y: ${radians(-60)}
    - name: right_camera
      x: 0.75
      y: 0.3
      P: ${radians(15)}
      Y: ${radians(0)}
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
      y: -0.2
wamv_p3d:
    - name: p3d_wamv
lidar:
    - name: lidar_wamv
      type: 16_beam
      P: ${radians(8)}
