wamv_camera:
    - name: middle_camera
      x: 0.85
      y: 0.0
wamv_gps:
    - name: gps_wamv
      x: -0.85
wamv_imu:
    - name: imu_wamv
wamv_p3d:
    - name: p3d_wamv
lidar:
    - name: lidar_wamv
      type: 32_beam
      P: ${radians(8)}
