engine:
  - prefix: "rear_left"
    position: "-2.25 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "rear_right"
    position: "-2.25 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "front_left"
    position: "1.75 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "front_right"
    position: "1.75 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0" 
  
